"""
Spin-triplet superconductivity solver — Python interface.

Computes long-range triplet correlations generated by inhomogeneous
magnetization with spin-active interface boundary conditions.

Pair types in ferromagnets:
    Singlet f₀:             short-range, decays as exp(−x/ξ_F)cos(x/ξ_F)
    Triplet m_s=0 (f₃):    short-range, decays as exp(−x/ξ_F)
    Equal-spin triplet:     long-range, decays as exp(−x/ξ_N)

Equal-spin triplets are generated at interfaces where magnetization
rotates between adjacent layers:
    f↑↑ ∝ sin(α) exp(−x/ξ_N)

where α is the misalignment angle.

See docs/theory/triplet_correlations.ipynb for details.

References:
    Bergeret, F.S. et al. (2005). Rev. Mod. Phys. 77, 1321.
    Houzet, M. & Buzdin, A.I. (2007). Phys. Rev. B 76, 060504.
"""

import numpy as np


_USE_NATIVE = False
try:
    from supermag._native import _triplet_solve as _native_triplet_solve
    _USE_NATIVE = True
except ImportError:
    pass


def solve(n_layers, thicknesses, magnetization_angles, n_grid=200,
          xi_F=1.0, xi_N=10.0):
    """
    Compute spin-triplet pair correlations in a magnetic multilayer.

    Models singlet-to-triplet conversion at interfaces with non-collinear
    magnetization. The equal-spin triplet component is long-range and
    maximal at 90 deg misalignment.

    Parameters
    ----------
    n_layers : int
        Number of layers.
    thicknesses : array_like
        Layer thicknesses (nm), shape (n_layers,).
    magnetization_angles : array_like
        Magnetization direction in each layer (rad), shape (n_layers,).
    n_grid : int, optional
        Total spatial grid points. Default: 200.
    xi_F : float, optional
        Short-range (ferromagnetic) coherence length (nm). Default: 1.0.
    xi_N : float, optional
        Long-range (triplet) coherence length (nm). Default: 10.0.

    Returns
    -------
    x : numpy.ndarray
        Position array (nm).
    f_triplet : numpy.ndarray
        Equal-spin triplet pair amplitude |f↑↑(x)|.
    """
    if _USE_NATIVE:
        return _native_triplet_solve(
            n_layers, np.ascontiguousarray(thicknesses, dtype=np.float64),
            np.ascontiguousarray(magnetization_angles, dtype=np.float64),
            xi_F, xi_N,
            n_grid)

    # Pure Python fallback
    thicknesses = np.asarray(thicknesses, dtype=np.float64)
    magnetization_angles = np.asarray(magnetization_angles, dtype=np.float64)

    total_thickness = np.sum(thicknesses)
    x = np.linspace(0, total_thickness, n_grid)

    # Compute f_triplet(x) by summing contributions from each interface
    f_triplet = np.zeros(n_grid)

    # Interface positions
    interface_positions = np.cumsum(thicknesses[:-1])

    for i, x_int in enumerate(interface_positions):
        # Misalignment angle between adjacent layers
        alpha = magnetization_angles[i + 1] - magnetization_angles[i]

        # Triplet amplitude ∝ sin(α)
        # Generated at interface, decays as exp(-|x - x_int|/ξ_N) (long-range)
        triplet_amplitude = np.sin(alpha)

        dist = np.abs(x - x_int)

        # Long-range equal-spin triplet  [EQ-12]
        f_long = np.abs(triplet_amplitude) * np.exp(-dist / xi_N)

        f_triplet += f_long

    return x, f_triplet
