"""
STUB — Spin-triplet superconductivity solver Python interface.

Computes long-range triplet correlations generated by inhomogeneous
magnetization with spin-active interface boundary conditions.

See docs/theory/triplet_correlations.ipynb for details.
"""

import numpy as np


def solve(n_layers, thicknesses, magnetization_angles, n_grid=200):
    """
    Compute spin-triplet pair correlations in a magnetic multilayer.

    Parameters
    ----------
    n_layers : int
        Number of layers.
    thicknesses : array_like
        Layer thicknesses (nm), shape (n_layers,).
    magnetization_angles : array_like
        Magnetization direction in each layer (rad), shape (n_layers,).
    n_grid : int, optional
        Total spatial grid points.

    Returns
    -------
    x : numpy.ndarray
        Position array (nm).
    f_triplet : numpy.ndarray
        Triplet pair amplitude.

    Raises
    ------
    NotImplementedError
        This solver is not yet implemented.
    """
    raise NotImplementedError(
        "Triplet solver not yet implemented. See docs/theory/triplet_correlations.ipynb"
    )
